//
// ContentVideoV3ResponseTextTracksInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct ContentVideoV3ResponseTextTracksInner: Content, Hashable {

    /** Text track identifier. */
    public var id: String
    /** URL to a text track file, usually .vtt files. */
    public var src: String
    /** Usually 'caption'. */
    public var kind: String
    /** Language code, e.g. 'en'. */
    public var language: String
    /** Whether the text track has been generated. */
    public var generated: Bool
    /** Whether the text track is processing. */
    public var processing: Bool

    public init(id: String, src: String, kind: String, language: String, generated: Bool, processing: Bool) {
        self.id = id
        self.src = src
        self.kind = kind
        self.language = language
        self.generated = generated
        self.processing = processing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case src
        case kind
        case language
        case generated
        case processing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(src, forKey: .src)
        try container.encode(kind, forKey: .kind)
        try container.encode(language, forKey: .language)
        try container.encode(generated, forKey: .generated)
        try container.encode(processing, forKey: .processing)
    }
}

