//
// UserStatusV3Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct UserStatusV3Response: Content, Hashable {

    public var selfUser: UserSelfV3Response?

    public init(selfUser: UserSelfV3Response? = nil) {
        self.selfUser = selfUser
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case selfUser
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(selfUser, forKey: .selfUser)
    }
}

