// APIs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Vapor

open class FloatplaneAPIClientAPI {
    public static var basePath = "https://www.floatplane.com"
    public static var customHeaders: HTTPHeaders = [:]
}
